### PR TITLE
GH36 fix skip bug

### LINKED ISSUE #36: Skip option is always set to the overwrite option
**Describe the bug**
I'm trying to get cookiecutter to overwrite an existing file when generating from the template however when I switch overwrite on, the file is also skipped because skip is turned on

The bug seems to have occurred in [main.py#L91](https://github.com/andrewthetechie/gha-cookiecutter/blob/7a1866088fa15434f9846af7b7a6e81a83019923/main.py#L91) where the value passed in for 'skip' is overwritten to be the value passed in for overwrite, and the condition is duplicated - perhaps a dodgy merge?

**To Reproduce**
1. Set up a workflow using this action
2. Set the overwrite and skip options to combinations of true/false
3. See that the skip value passed in is ignored

**Expected behavior**
* Values passed in explicitly for overwrite and skip should be kept
* The documentation should clarify which one takes priority if both are set to true as they are mutually exclusive

**Screenshots**

Screenshot 2024-06-12 at 12 53 28

### PR DESCRIPTION
**Pull request by larmitage-bjss**
To fix #36

Assumed the intention was for the overwrite option to take priority - if overwrite is set to true then skip is set to false

Updated descriptions of inputs to make this clearer

### CODE REVIEW

**Comment by andrewthetechie** [comment]
@all-contributors please add @larmitage-bjss for code and bug reports

**Comment by andrewthetechie** [comment]
@larmitage-bjss thank you very much for finding and fixing this bug.

**Comment by larmitage-bjss** [comment]
Thanks very much for the speedy response!

**Comment by andrewthetechie** [comment]
@larmitage-bjss 1.3.2 is released.

Your timing was perfect on filing this issue, I was just sitting down with my morning coffee :)

**Pull request merged**
